# Generated by Django 3.2.3 on 2021-07-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RutUsuario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Colaborador')),
                ('NombreCom', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('Telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('Direccion', models.CharField(max_length=60, verbose_name='Dirección')),
                ('email', models.CharField(max_length=70, verbose_name='Email')),
                ('Pais', models.CharField(max_length=40, verbose_name='País')),
            ],
        ),
    ]
