# Generated by Django 3.2.3 on 2021-07-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Foto',
            new_name='image',
        ),
    ]
