# Generated by Django 3.2.3 on 2021-07-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_foto_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
