# Generated by Django 3.2.3 on 2021-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(max_length=50)),
            ],
        ),
    ]
