# Generated by Django 3.2.3 on 2021-07-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Pais',
        ),
        migrations.AddField(
            model_name='usuario',
            name='idPais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais'),
        ),
    ]
